// <auto-generated />
//
// To parse this JSON data, add NuGet 'System.Text.Json' then do:
//
//    using Klinkby.Borigo2iCal.Domain;
//
//    var usersResponse = UsersResponse.FromJson(jsonString);
#nullable enable
#pragma warning disable CS8618
#pragma warning disable CS8601
#pragma warning disable CS8603

namespace Klinkby.Borigo2iCal.Domain
{
    using System;
    using System.Collections.Generic;

    using System.Text.Json;
    using System.Text.Json.Serialization;
    using System.Globalization;
    using J = System.Text.Json.Serialization.JsonPropertyNameAttribute;
    using N = System.Text.Json.Serialization.JsonIgnoreCondition;

    public partial class UsersResponse
    {
        [J("list")] public User[] Users { get; set; }
    }

    public partial class User
    {
        [J("id")]                                                                   public long Id { get; set; }                    
        [J("type")]                                                                 public string Type { get; set; }              
        [J("email")]                                                                public string Email { get; set; }               
        [J("firstName")]                                                            public string FirstName { get; set; }           
        [J("lastName")]                                                             public string LastName { get; set; }            
        [J("phone")]                                                                public string Phone { get; set; }               
        [J("emergencyContact")]                                                     public string EmergencyContact { get; set; }    
        [J("dateOfBirth")]                                                          public DateTimeOffset? DateOfBirth { get; set; }
        [J("description")]                                                          public string Description { get; set; }         
        [J("uiStorage")]                                                            public string UiStorage { get; set; }           
        [J("role")]                                                                 public string Role { get; set; }                  
        [J("roles")]                                                                public string[] Roles { get; set; }             
        [J("avatar")]                                                               public Uri Avatar { get; set; }                 
        [J("alias")]                                                                public string Alias { get; set; }               
        [J("locationId")]                                                           public long LocationId { get; set; }            
        [J("isFirstLogin")]                                                         public bool IsFirstLogin { get; set; }          
        [J("lastLogin")]                                                            public DateTimeOffset? LastLogin { get; set; }  
        [J("inviteSent")]                                                           public DateTimeOffset? InviteSent { get; set; } 
        [J("created")]                                                              public DateTimeOffset Created { get; set; }     
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)][J("isMinor")] public bool? IsMinor { get; set; }              
    }


    public partial class UsersResponse
    {
        public static UsersResponse FromJson(string json) => JsonSerializer.Deserialize<UsersResponse>(json, Klinkby.Borigo2iCal.Domain.Converter.Settings);
    }

    internal static partial class Serialize
    {
        public static string ToJson(this UsersResponse self) => JsonSerializer.Serialize(self, Klinkby.Borigo2iCal.Domain.Converter.Settings);
    }


    
}
#pragma warning restore CS8618
#pragma warning restore CS8601
#pragma warning restore CS8603
